name: codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  upload-to-codecov:
    runs-on: ubuntu-latest
    steps:

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
